### ISSUE TITLE
Displaying scores on the website

### ISSUE THREAD

**Issue by Setredid** [SunriseCommunity/Sunrise#33]
More of a suggestion, than an issue - can the difficulty title and time of submission get more separated?
Maybe with a "-"? Like:

Pain - 1 week ago

![image](https://github.com/user-attachments/assets/376c5207-4036-4f33-8875-0a48f9bf9612)

Thanks!

**Comment by richardscull** [comment]
Hey, @Setredid ! Thanks for the suggestion! 😸 

It was previously separated by a slight change of color, but looks like that it didn't work as good...
By your suggestion, changed font size of time of submission to a smaller one, made it darker and also made it italic. 

![image](https://github.com/user-attachments/assets/8117ee4b-4014-40d3-a1d9-b983567c1d69)
This change is already live on the website, but if you want me to update it somehow, please note. Otherwise, I will close this issue soon.

**Comment by Setredid** [comment]
Looks much better now! Please feel free to close the issue.
