### ISSUE TITLE
Appeal(for a friend) - paranoid

### ISSUE THREAD

**Issue by Setredid** [SunriseCommunity/Sunrise#34]
My friend's account was created on December 24, and after playing one 4,9* map with 5 misses, it got restricted. Is it a mistake? Can the ban be removed? Nickname: paranoid

**Comment by Setredid** [comment]
P.S. Didn't know how to contact you outside of Github, sorry

**Comment by richardscull** [comment]
Hello, thanks for all info provided.

This is unexpected behavior was caused by wrongly checking user's osu! Version and was fixed today in this patch: https://github.com/SunriseCommunity/Sunrise/commit/bf9ebf22fca2528b84c520302c7102f0ed5e918a

I already unrestricted your friend, and so I apologize profusely for the current situation. 🙇‍♂️

P.S: Feel free to reach out to me through Discord at [richardscull](https://discordapp.com/users/228223085759692802) for this kind of matters.
